spring:
  application:
    name: microservice-jboot
    enable-csrf: false
  datasource:
    username: jboot
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.Oracle10gDialect
security:
  user:
    name: sys
    password: password
    roles: USER
management:
  endpoints:
    web:
      exposure:
        include: "*"
# eureka config
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9001/eureka/,http://localhost:9000/eureka/
zuul:
  routes:
    user-service-api:
     path: /api-users/**
     service-id: users-service
     
     
logging:
 level:
  root: DEBUG
  org.springframework.security: DEBUG