
package com.github.sawied.services.appmanagment;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "appMgmt", targetNamespace = "http://www.github.com/sawied/services/appManagment")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.github.sawied.bean.base.ObjectFactory.class,
    com.github.sawied.bean.common.ObjectFactory.class,
    com.github.sawied.services.appmanagment.ObjectFactory.class
})
public interface AppMgmt {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.github.sawied.services.appmanagment.RetrvApplicationInfoResponse
     * @throws FaultMsg
     */
    @WebMethod(action = "http://www.danan.org/appManagment/retrvApplicationInfo")
    @WebResult(name = "retrvApplicationInfoResponse", targetNamespace = "http://www.github.com/sawied/services/appManagment", partName = "parameters")
    public RetrvApplicationInfoResponse retrvApplicationInfo(
        @WebParam(name = "retrvApplicationInfoRequest", targetNamespace = "http://www.github.com/sawied/services/appManagment", partName = "parameters")
        RetrvApplicationInfoRequest parameters)
        throws FaultMsg
    ;

}
