
package com.github.sawied.services.appmanagment;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AppMgmtService", targetNamespace = "http://www.github.com/sawied/services/appManagment", wsdlLocation = "file:/E:/work/swp/agent/src/main/resources/sawied/agent/wsdl/application.wsdl")
public class AppMgmtService
    extends Service
{

    private final static URL APPMGMTSERVICE_WSDL_LOCATION;
    private final static WebServiceException APPMGMTSERVICE_EXCEPTION;
    private final static QName APPMGMTSERVICE_QNAME = new QName("http://www.github.com/sawied/services/appManagment", "AppMgmtService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/E:/work/swp/agent/src/main/resources/sawied/agent/wsdl/application.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        APPMGMTSERVICE_WSDL_LOCATION = url;
        APPMGMTSERVICE_EXCEPTION = e;
    }

    public AppMgmtService() {
        super(__getWsdlLocation(), APPMGMTSERVICE_QNAME);
    }

    public AppMgmtService(WebServiceFeature... features) {
        super(__getWsdlLocation(), APPMGMTSERVICE_QNAME, features);
    }

    public AppMgmtService(URL wsdlLocation) {
        super(wsdlLocation, APPMGMTSERVICE_QNAME);
    }

    public AppMgmtService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, APPMGMTSERVICE_QNAME, features);
    }

    public AppMgmtService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AppMgmtService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AppMgmt
     */
    @WebEndpoint(name = "appMgmtPort")
    public AppMgmt getAppMgmtPort() {
        return super.getPort(new QName("http://www.github.com/sawied/services/appManagment", "appMgmtPort"), AppMgmt.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AppMgmt
     */
    @WebEndpoint(name = "appMgmtPort")
    public AppMgmt getAppMgmtPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.github.com/sawied/services/appManagment", "appMgmtPort"), AppMgmt.class, features);
    }

    private static URL __getWsdlLocation() {
        if (APPMGMTSERVICE_EXCEPTION!= null) {
            throw APPMGMTSERVICE_EXCEPTION;
        }
        return APPMGMTSERVICE_WSDL_LOCATION;
    }

}
