
package org.danan.appmanagment;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "appMgmt", targetNamespace = "http://www.danan.org/appManagment/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    org.danan.appmanagment.ObjectFactory.class,
    org.danan.bean.commonsegment.ObjectFactory.class
})
public interface AppMgmt {


    /**
     * 
     * @param parameters
     * @return
     *     returns org.danan.appmanagment.RetrvApplicationInfoResponse
     * @throws FaultMsg
     */
    @WebMethod(action = "http://www.danan.org/appManagment/retrvApplicationInfo")
    @WebResult(name = "retrvApplicationInfoResponse", targetNamespace = "http://www.danan.org/appManagment/", partName = "parameters")
    public RetrvApplicationInfoResponse retrvApplicationInfo(
        @WebParam(name = "retrvApplicationInfoRequest", targetNamespace = "http://www.danan.org/appManagment/", partName = "parameters")
        RetrvApplicationInfoRequest parameters)
        throws FaultMsg
    ;

}
