
package org.danan.appmanagment;

import javax.xml.ws.WebFault;
import org.danan.bean.commonsegment.FaultInfo;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "BusinessException", targetNamespace = "http://www.danan.org/appManagment/")
public class FaultMsg
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FaultInfo faultInfo;
    

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public FaultMsg(String message, FaultInfo faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public FaultMsg(String message, FaultInfo faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: org.danan.bean.commonsegment.FaultInfo
     */
    public FaultInfo getFaultInfo() {
        return faultInfo;
    }

}
