define({
	dummy:false,
	services:{
		"retrieveApplist":{			
			method:"GET",
			url:"service/getApplist/{appId}",
			headers:{
				"Context-type":"application/json"
			}
		},
		"addApp":{
			method:"POST",
			"url":"service/add"
		},
		"delete":{
			method:"delete",
			"url":"application/{appId}",
		}
	}
	
});