server:
    port: ${port:8000}
spring:
  main:
    banner-mode: "console"
  application:
    name: service-websocket
    
    
# eureka config

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    enabled: true
    service-url:
      defaultZone: http://localhost:9000/eureka/