<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions  xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.github.com/sawied/services/appManagment" xmlns:cm="http://www.github.com/sawied/bean/common" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"  name="appManagment" targetNamespace="http://www.github.com/sawied/services/appManagment">
 
  <wsdl:types>
   <xsd:schema targetNamespace="http://www.github.com/sawied/services/appManagment" xmlns:cm="http://www.github.com/sawied/bean/common">
   	<xsd:import schemaLocation="common.xsd" namespace="http://www.github.com/sawied/bean/common"></xsd:import>
   	<xsd:element name="retrvApplicationInfoRequest">
   		<xsd:complexType>
   			<xsd:sequence>
   				<xsd:element name="in" type="xsd:string" />
   			</xsd:sequence>
   		</xsd:complexType>
   	</xsd:element>
   	<xsd:element name="retrvApplicationInfoResponse">
   		<xsd:complexType>
   			<xsd:sequence>
   				<xsd:element name="out" type="xsd:string" />
   				<xsd:element name="info" type="cm:customer"></xsd:element>
   			</xsd:sequence>
   		</xsd:complexType>
   	</xsd:element>
   	
   	<xsd:element name="BusinessException" type="cm:faultInfo"></xsd:element>
   </xsd:schema>
  </wsdl:types>
  
  
  <wsdl:message name="retrvApplicationInfoRstMsg">
    <wsdl:part element="tns:retrvApplicationInfoRequest" name="parameters"/>
  </wsdl:message>
  
  <wsdl:message name="retrvApplicationInfoRspMsg">
    <wsdl:part element="tns:retrvApplicationInfoResponse" name="parameters"/>
  </wsdl:message>
  
  <wsdl:message name="faultMsg">
   <wsdl:part name="parameters" element="tns:BusinessException"></wsdl:part>
  </wsdl:message>
  
  
  <wsdl:portType name="appMgmt">
    <wsdl:operation name="retrvApplicationInfo" xmlns="default namespace">
      <wsdl:input message="tns:retrvApplicationInfoRstMsg"/>
      <wsdl:output message="tns:retrvApplicationInfoRspMsg"/>
      <wsdl:fault name="fault" message="tns:faultMsg"></wsdl:fault>
    </wsdl:operation>
  </wsdl:portType>
  
  <wsdl:binding name="AppMgmtBinding" type="tns:appMgmt">
  	<soap12:binding
  		transport="http://www.w3.org/2003/05/soap/bindings/HTTP/"
  		style="document" />
  	<wsdl:operation name="retrvApplicationInfo">
  		<soap12:operation
  			soapAction="http://www.danan.org/appManagment/retrvApplicationInfo" />
  		<wsdl:input>
  			<soap12:body use="literal" />
  		</wsdl:input>
  		<wsdl:output>
  			<soap12:body use="literal" />
  		</wsdl:output>
  		<wsdl:fault name="fault">
  			<soap12:fault name="fault" use="literal" />
  		</wsdl:fault>
  	</wsdl:operation>
  </wsdl:binding>

  <wsdl:service name="AppMgmtService">
    <wsdl:port binding="tns:AppMgmtBinding" name="appMgmtPort">
      <soap12:address location="http://localhost:9080/"/>
    </wsdl:port>
  </wsdl:service>
  
</wsdl:definitions>
