spring:
  application:
    name: microservice-experience
    

server:
  port: 9003

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9001/eureka/,http://localhost:9000/eureka/