server:
  port: 9000
  
debug: true
management:
  security:
    enabled: false

trust-oauth2:
 base-url: http://localhost:8888/microservice-authorization-SNAPSHOT/
 access-token-url: ${trust-oauth2.base-url}/oauth/token
 
zuul:
  routes:
    ao:
     path: /ao/**
     url: http://localhost:8888/microservice-resource-SNAPSHOT/
     custom-sensitive-headers: true
     sensitive-headers: Cookie,Set-Cookie
    auth:
      path: /auth/**
      url: ${trust-oauth2.base-url}
      custom-sensitive-headers: true
      sensitive-headers: Cookie,Set-Cookie
         